import org.json.JSONObject;

import javax.imageio.ImageIO;
import javax.jms.JMSException;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.synth.SynthStyle;
import java.awt.*;
import java.awt.font.TextAttribute;
import java.io.File;
import java.io.IOException;
import java.util.Collections;
import java.util.List;

public class ReceiverScreen {
  private JTextField messageTextField;
  private JButton sendButton;
  private JList requestsList;
  private JPanel mainPanel;
  private JFrame frame;

  private DefaultListModel requestsListModel;
  private Receiver receiver = new Receiver(new Runnable() {
    @Override
    public void run() {
      updateRequestsList(receiver.getMessagesTitles());
      frame.toFront();
    }
  });

  private void updateRequestsList(List messages) {
    requestsListModel.removeAllElements();
    requestsListModel.addAll(messages);
  }

  public ReceiverScreen(JFrame frame) {
    $$$setupUI$$$();
    this.frame = frame;
    sendButton.addActionListener(actionEvent -> {
      if (requestsList.getSelectedIndex() != -1) {
        String replyText = "Works!";
        if (!messageTextField.getText().equals("")) replyText = messageTextField.getText();

        Boolean important = false;
        try {
          String msgText = receiver.getReceivedMessages().get(requestsList.getSelectedIndex()).getText();
          JSONObject msgJson = new JSONObject(msgText);
          important = msgJson.getBoolean("important");
        } catch (Exception e) {
        }

        receiver.replyMessage(requestsList.getSelectedIndex(), replyText, important);
        messageTextField.setText("");
      }
    });
    requestsList.addListSelectionListener(new ListSelectionListener() {
      @Override
      public void valueChanged(ListSelectionEvent listSelectionEvent) {
        if (listSelectionEvent.getValueIsAdjusting() == false) {

          if (requestsList.getSelectedIndex() == -1) {
            //No selection, disable fire button.
            sendButton.setEnabled(false);
            messageTextField.setEnabled(false);
          } else {
            //Selection, enable the fire button.
            sendButton.setEnabled(true);
            messageTextField.setEnabled(true);
          }
        }
      }
    });
  }

  public static void main(String[] args) {
    JFrame frame = new JFrame("Flights Booking Agency");
    try {
      frame.setIconImage(ImageIO.read(new File("img/inbox-alt.png")));
    } catch (IOException e) {
    }
    frame.setContentPane(new ReceiverScreen(frame).mainPanel);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.setVisible(true);
  }

  private void createUIComponents() {
    requestsList = new JList();
    requestsList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    requestsListModel = new DefaultListModel();
    requestsList.setModel(requestsListModel);
    requestsList.setCellRenderer(new DefaultListCellRenderer() {
      @Override
      public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        try {
          String msgText = receiver.getReceivedMessages().get(index).getText();
          JSONObject msgJson = new JSONObject(msgText);

          try {
            Boolean important = msgJson.getBoolean("important");
            if (important) {
              Font font = getFont();

              font = font.deriveFont(
                Collections.singletonMap(
                  TextAttribute.WEIGHT, TextAttribute.WEIGHT_BOLD));

              setFont(font);
            }
          } catch (Exception e) {
          }

          String hexColor = msgJson.getString("color");
          setForeground(Color.decode(hexColor));

        } catch (JMSException e) {
        }
        return c;
      }
    });

    updateRequestsList(receiver.getMessagesTitles());
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    mainPanel = new JPanel();
    mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(8, 8, 8, 8), -1, -1));
    final JLabel label1 = new JLabel();
    label1.setText("Questions");
    mainPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
    mainPanel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    messageTextField = new JTextField();
    messageTextField.setEnabled(false);
    messageTextField.setText("");
    messageTextField.setToolTipText("Type a message");
    panel1.add(messageTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, -1), null, 0, false));
    sendButton = new JButton();
    sendButton.setEnabled(false);
    sendButton.setText("Reply");
    panel1.add(sendButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JScrollPane scrollPane1 = new JScrollPane();
    mainPanel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(350, 300), null, 0, false));
    Font requestsListFont = this.$$$getFont$$$(null, Font.PLAIN, -1, requestsList.getFont());
    if (requestsListFont != null) requestsList.setFont(requestsListFont);
    requestsList.setSelectionBackground(new Color(-2236963));
    scrollPane1.setViewportView(requestsList);
  }

  /**
   * @noinspection ALL
   */
  private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
    if (currentFont == null) return null;
    String resultName;
    if (fontName == null) {
      resultName = currentFont.getName();
    } else {
      Font testFont = new Font(fontName, Font.PLAIN, 10);
      if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
        resultName = fontName;
      } else {
        resultName = currentFont.getName();
      }
    }
    return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }

}
